### ISSUE TITLE
Trending scraper fail

### ISSUE THREAD

**Issue by taldcroft** [sot/twiki-wg#16]
@johnny1up -- seems like a problem in the latest update that I merged.

```
WARNING - '/proj/sot/ska3/flight/share/twiki-wg/ssawg_trending_scraper.py --data-dir /proj/sot/ska3/flight/data/twiki-wg' returned non-zero status: 256
Traceback (most recent call last):
  File "/proj/sot/ska3/flight/share/twiki-wg/ssawg_trending_scraper.py", line 240, in <module>
    trending_blocks[page] = page_class(page)
  File "/proj/sot/ska3/flight/share/twiki-wg/ssawg_trending_scraper.py", line 102, in __init__
    self.url, self.current_url = self.get_url()
  File "/proj/sot/ska3/flight/share/twiki-wg/ssawg_trending_scraper.py", line 209, in get_url
    last_month = DateTime(DateTime() + timedelta(days=-27))
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/Chandra/Time/Time.py", line 715, in __add__
    return DateTime(self.jd + days, format='jd')
TypeError: unsupported operand type(s) for +: 'float' and 'datetime.timedelta'
```

**Comment by jeanconn** [comment]
I don't think this a problem anymore
